site_name: "Samitch - Developer Portfolio"
site_description: "Github Pages site for Samitch"
site_url: https://Samitch-media.github.io/
# These additional attributes control the 'edit' button in the tech doc
# repo_url: https://github.com/Samitch-media/Samitch-media.github.io
# edit_uri: edit/main/docs

nav:
  - Home: index.md
  - Examples: examples.md
  - Projects:
    - Mangata & Gallo: projects/mangata-gallo/project.md

plugins:
  - git-revision-date-localized
  # - search
  # - optimize:
  #     enabled: !ENV [CI, false]
  # - social:
  #     enabled: !ENV [CI, false]


# Example of how to enable a markdown extension
markdown_extensions:
  # Example of how to configure an extension variable
  - admonition
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.highlight
  - pymdownx.extra
  - pymdownx.tabbed
  - pymdownx.tilde
  - mdx_truly_sane_lists
  - pymdownx.tasklist:
      custom_checkbox: true
  - meta
  - attr_list
  - tables
  # - toc

# Example of how to configure extra CSS in the markdown rendering.
# Please see the mkdocs documentation for more details: https://www.mkdocs.org/user-guide/configuration/#extra_css
extra_css:
  - assets/css/styles.css
  - assets/css/tabbed.css
  - assets/css/parallax.css

theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode
    # - media: "(prefers-color-scheme: light)"
    #   scheme: default
    #   primary: black
    #   accent: green
    #   toggle:
    #     icon: material/weather-night
    #     name: Switch to dark mode
    # - media: "(prefers-color-scheme: dark)"
    - scheme: slate
      primary: black
      accent: green
      # toggle:
      #   icon: material/weather-sunny
      #   name: Switch to light mode

  features:
    - navigation.instant
    - navigation.top
    # - navigation.tabs
    - navigation.path
    - navigation.footer
    - navigation.tracking
    # - toc.integrate
    # - header.autohide
  language: en
  logo: images/logo/SamitchLogo.jpg

  favicon: images/logo/SamitchIcon.ico

  icon:
    repo: fontawesome/brands/git-alt
  # font:
  #   text: Fira Sans
  #   code: Ubuntu Mono


extra:
  social:
  - icon: fontawesome/brands/github
    link: https://Samitch-media.github.io
  - icon: fontawesome/brands/x-twitter
    link: https://x.com/Samitch_US
  - icon: fontawesome/brands/discord
    link: https://discordapp.com/users/122786737150754819
  # consent:
  #   title: Cookie consent
  #   description: >- 
  #     We use cookies to recognize your repeated visits and preferences, as well
  #     as to measure the effectiveness of our documentation and whether users
  #     find what they're searching for. With your consent, you're helping us to
  #     make our documentation better.
